# This file was generated by GoReleaser. DO NOT EDIT.
cask "7331" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "8eb7c79dffdd8fa3de077de813c5f08231e1434b23bb1bdd28f3d714c9986faf"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4e8cb6e7e82c56c2a36d436cda298be25d492b8a1c131f68da6f4d10cadca4ef"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9aefbe8f8b42833e2092d980f440dc3de55e3eabc95fbc04fbc5b2ea5df60489"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f13004e86ee45f82ae7768815948becdfb92569ffebec7a50df98a7d3a0f98c"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_linux_arm64.tar.gz"
    end
  end

  name "7331"
  desc "Anonymous image uploads from the command line"
  homepage "https://7331.cloud/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7331"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/7331"]
    end
  end

  # No zap stanza required

end
