# This file was generated by GoReleaser. DO NOT EDIT.
cask "7331" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "43aac732b8db768795bca543c5e906a3105f15d4021d7ffb6c6110afbb53c8d4"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba981994cc60c3b9b4cf630ed3b1bd95eb102bffff93b1ca6a4a2db34a394885"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d402822accdb290b9c52f428402bd4a64cec352abb83d89ce4ece56a59d21cc5"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff36b7add4c69036bb83be4e079af4fd62f096b449e2a4b9082490bac3c2633a"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_linux_arm64.tar.gz"
    end
  end

  name "7331"
  desc "Anonymous image uploads from the command line"
  homepage "https://7331.cloud/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7331"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/7331"]
    end
  end

  # No zap stanza required

end
