# This file was generated by GoReleaser. DO NOT EDIT.
cask "7331" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5151c14d399bd0a950585036b6ba22999d29529368dd958dda60bf6c4fb71ffd"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f22ac1159eb1cfcf1fc7b94f39e4ece7a65344ffaee4d8e528288361778ae1c"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c11b011cfcfa7696d7089d414868a858ff7623ceacd2dc0338962907fe8d0a1"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cd52b3281602e374d5dcb23d3741be4fd7cf1ac329f93723107d7c0ba6eb4cd"
      url "https://github.com/1337lean/7331-cli/releases/download/v#{version}/7331_#{version}_linux_arm64.tar.gz"
    end
  end

  name "7331"
  desc "Anonymous image uploads from the command line"
  homepage "https://7331.cloud/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7331"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/7331"]
    end
  end

  # No zap stanza required

end
